const schema = {
  api: "https://jkumarapi.axiomos.in/event",
  title: "Scheduled Events",
  columns: [
    {
      label: "Title",
      field: "title",
      type: "text",
      filter: true,
    },
    {
      label: "Description",
      field: "description",
      type: "textarea",
    },
    {
      label: "Category",
      field: "category",
      type: "dropdown",
      options: [
        "Toolbox Talk",
        "Induction",
        "Safety Training",
        "Audit",
        "Inspection",
        "EHS Meeting",
        "Mock Drill",
        "Safety Walkdown",
        "Emergency Drill",
        "General Event",
      ],
      filter: true,
    },
    {
      label: "Meeting Link",
      field: "meetingLink",
      type: "text",
    },
    {
      label: "Start Date",
      field: "startDate",
      type: "date",
      filter: true,
    },
    {
      label: "End Date",
      field: "endDate",
      type: "date",
      filter: true,
    },
    {
      label: "Start Time",
      field: "startTime",
      type: "time",
    },
    {
      label: "End Time",
      field: "endTime",
      type: "time",
    },
    {
      label: "Duration (Minutes)",
      field: "durationMinutes",
      type: "number",
    },
    {
      label: "Geotagging",
      field: "geotagging",
      type: "geolocation",
    },
    {
      label: "Project",
      field: "project.projectName",
      type: "dropdown",
      api: "https://jkumarapi.axiomos.in/projects",
      apiTitle: "projectName",
      filter: true,
    },
    {
      label: "Area",
      field: "area",
      type: "text",
      filter: true,
    },
    {
      label: "Created By",
      field: "createdBy.name",
      type: "dropdown",
      api: "https://jkumarapi.axiomos.in/user",
      apiTitle: "name",
      filter: true,
    },
    {
      label: "Assigned To",
      field: "assignedTo.name",
      type: "checkbox",
      array: true,
      api: "https://jkumarapi.axiomos.in/user",
      apiTitle: "name",
      filter: true,
      details: true,
      boxShow: ["userId", "name", "designation", "emailId", "phone"],
    },
    {
      label: "Escalation To",
      field: "escalationTo.name",
      type: "checkbox",
      array: true,
      api: "https://jkumarapi.axiomos.in/user",
      apiTitle: "name",
      filter: true,
      details: true,
      boxShow: ["userId", "name", "designation", "emailId", "phone"],
    },
    {
      label: "Recurrence Settings",
      field: "recurrence",
      type: "subObject",
      subFields: [
        {
          label: "Frequency",
          field: "frequency",
          type: "dropdown",
          options: ["none", "daily", "weekly", "monthly", "yearly"],
        },
        {
          label: "Interval",
          field: "interval",
          type: "number",
        },
        {
          label: "Days of Week",
          field: "daysOfWeek",
          type: "dropdown",
          options: ["1", "2", "3", "4", "5", "6", "7"],
        },
        {
          label: "End Recurrence",
          field: "endRecurrence",
          type: "date",
        },
        {
          label: "Auto Generate Instances",
          field: "autoGenerateInstances",
          type: "boolean",
        },
      ],
    },
    {
      label: "Reminder Settings",
      field: "reminders",
      type: "subObject",
      subFields: [
        {
          label: "Time Before (Minutes)",
          field: "timeBefore",
          type: "number",
        },
        {
          label: "Push Notification",
          field: "push",
          type: "boolean",
        },
        {
          label: "Email",
          field: "email",
          type: "boolean",
        },
        {
          label: "SMS",
          field: "sms",
          type: "boolean",
        },
      ],
    },
    {
      label: "Participants",
      field: "participants",
      type: "subObject",
      subFields: [
        {
          label: "Labour",
          field: "labour",
          type: "dropdown",
          api: "https://jkumarapi.axiomos.in/labour",
          apiTitle: "name",
        },
        {
          label: "Status",
          field: "status",
          type: "dropdown",
          options: ["Present", "Absent", "Late", "Excused"],
        },
        {
          label: "Marked By",
          field: "markedBy",
          type: "dropdown",
          api: "https://jkumarapi.axiomos.in/user",
          apiTitle: "name",
        },
        {
          label: "Marked At",
          field: "markedAt",
          type: "date",
        },
      ],
    },
    {
      label: "Evidence Photo",
      field: "evidencePhotos",
      type: "imageLink",
      uploadApi: "https://jkumarapi.axiomos.in/event/image",
    },
    {
      label: "Status",
      field: "status",
      type: "dropdown",
      options: [
        "Upcoming",
        "In Progress",
        "Completed",
        "Cancelled",
        "Delayed",
        "Expired",
      ],
      filter: true,
    },
    {
      label: "Auto Status Update",
      field: "autoStatusUpdate",
      type: "boolean",
    },
    {
      label: "Is Overdue",
      field: "isOverdue",
      type: "boolean",
      edit: false,
    },
    {
      label: "Created At",
      field: "createdAt",
      type: "date",
      filter: true,
    },
    {
      label: "Updated At",
      field: "updatedAt",
      type: "date",
      filter: true,
    },
  ],
};
