// for okgNodes
const TABLE_CONFIG = {
  api: "https://legalobackend.axiomos.in/okgnodes",
  title: "OKG Nodes",
  columns: [
    {
      label: "Organization",
      field: "orgId.name",
      type: "dropdown",
      api: "https://legalobackend.axiomos.in/orgs",
      apiTitle: "name",
      filter: "true",
    },
    {
      label: "Node ID",
      field: "nodeId",
      type: "text",
      required: "true",
      filter: "true",
    },
    {
      label: "Node Type",
      field: "nodeType",
      type: "dropdown",
      options: ["CITATION", "OBLIGATION", "CONCEPT"],
      required: "true",
      filter: "true",
    },
    {
      label: "Title",
      field: "title",
      type: "text",
      required: "true",
      filter: "true",
    },
    {
      label: "Content",
      field: "content",
      type: "textarea",
    },
    {
      label: "Source URI",
      field: "sourceUri",
      type: "text",
      filter: "true",
    },
    {
      label: "Statute Reference",
      field: "statuteReference",
      type: "text",
      filter: "true",
    },
    {
      label: "Language",
      field: "language",
      type: "text",
      filter: "true",
    },
    {
      label: "Jurisdiction",
      field: "jurisdiction",
      type: "text",
      filter: "true",
    },
    {
      label: "Tags",
      field: "tags",
      type: "arrayText",
      array: "true",
      placeholder: "Add tags (press Enter)",
    },
    {
      label: "Metadata",
      field: "metadata",
      type: "json",
      required: "true",
    },
    {
      label: "Version",
      field: "version",
      type: "number",
      filter: "true",
    },
    {
      label: "Status",
      field: "status",
      type: "dropdown",
      options: ["DRAFT", "PUBLISHED", "ARCHIVED"],
      filter: "true",
    },
    {
      label: "Active",
      field: "isActive",
      type: "boolean",
      filter: "true",
    },
    {
      label: "Created By",
      field: "createdBy.name",
      type: "dropdown",
      api: "https://legalobackend.axiomos.in/users",
      apiTitle: "name",
      filter: "true",
    },
    {
      label: "Updated By",
      field: "updatedBy.name",
      type: "dropdown",
      api: "https://legalobackend.axiomos.in/users",
      apiTitle: "name",
      filter: "true",
    },
    {
      label: "Created At",
      field: "createdAt",
      type: "Date",
      filter: "true",
    },
    {
      label: "Updated At",
      field: "updatedAt",
      type: "Date",
      filter: "true",
    },
  ],
  actions: {
    create: true,
    edit: true,
    delete: false,
  },
};

// for okgedges

// const TABLE_CONFIG = {
//   api: "https://legalobackend.axiomos.in/okgedges",
//   title: "OKG Edges",
//   columns: [
//     {
//       label: "Organization",
//       field: "orgId.name",
//       type: "dropdown",
//       api: "https://legalobackend.axiomos.in/orgs",
//       apiTitle: "name",
//       filter: "true",
//     },
//     {
//       label: "From Node ID",
//       field: "fromNodeId",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "To Node ID",
//       field: "toNodeId",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Edge Type",
//       field: "edgeType",
//       type: "dropdown",
//       options: ["CITES", "REQUIRES", "RELATES_TO"],
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Weight",
//       field: "weight",
//       type: "number",
//       filter: "true",
//     },
//     {
//       label: "Confidence Score",
//       field: "confidenceScore",
//       type: "number",
//       filter: "true",
//     },
//     {
//       label: "Created Via",
//       field: "createdVia",
//       type: "dropdown",
//       options: ["MANUAL", "MODEL", "IMPORT"],
//       filter: "true",
//     },
//     {
//       label: "Status",
//       field: "status",
//       type: "dropdown",
//       options: ["ACTIVE", "DEPRECATED"],
//       filter: "true",
//     },
//     {
//       label: "Active",
//       field: "isActive",
//       type: "boolean",
//       filter: "true",
//     },
//     {
//       label: "Created By",
//       field: "createdBy.name",
//       type: "dropdown",
//       api: "https://legalobackend.axiomos.in/users",
//       apiTitle: "name",
//       filter: "true",
//     },
//     {
//       label: "Metadata",
//       field: "metadata",
//       type: "json",
//       required: "true",
//     },
//     {
//       label: "Version",
//       field: "version",
//       type: "number",
//       filter: "true",
//     },
//     {
//       label: "Created At",
//       field: "createdAt",
//       type: "Date",
//       filter: "true",
//     },
//     {
//       label: "Updated At",
//       field: "updatedAt",
//       type: "Date",
//       filter: "true",
//     },
//   ],
//   actions: {
//     create: true,
//     edit: true,
//     delete: false,
//   },
// };

// const TABLE_CONFIG = {
//   api: "https://legalobackend.axiomos.in/dpdp_sections",
//   title: "DPDP Sections",
//   columns: [
//     {
//       label: "Section ID",
//       field: "section_id",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Category",
//       field: "category",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Title",
//       field: "title",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Created At",
//       field: "createdAt",
//       type: "Date",
//       filter: "true",
//     },
//     {
//       label: "Updated At",
//       field: "updatedAt",
//       type: "Date",
//       filter: "true",
//     },
//   ],
//   actions: {
//     create: true,
//     edit: true,
//     delete: false,
//   },
// };

// for citations
// const TABLE_CONFIG = {
//   api: "https://legalobackend.axiomos.in/dpdp_citations",
//   title: "DPDP Citations",
//   columns: [
//     {
//       label: "Node ID",
//       field: "node_id",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Node Type",
//       field: "node_type",
//       type: "dropdown",
//       options: ["CITATION"],
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Citation Key",
//       field: "key",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Act",
//       field: "act",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Jurisdiction",
//       field: "jurisdiction",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Section",
//       field: "section",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Title",
//       field: "title",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Summary",
//       field: "summary",
//       type: "textarea",
//       required: "true",
//     },
//     {
//       label: "Source Type",
//       field: "source_type",
//       type: "dropdown",
//       options: [
//         "primary_legislation",
//         "subordinate_legislation",
//         "judgment",
//         "guideline",
//         "regulatory_notice",
//       ],
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Effective Date",
//       field: "effective_date",
//       type: "Date",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Confidence",
//       field: "confidence",
//       type: "dropdown",
//       options: ["low", "medium", "high"],
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Source URL",
//       field: "source_url",
//       type: "text",
//       required: "true",
//       filter: "true",
//     },
//     {
//       label: "Created At",
//       field: "created_at",
//       type: "Date",
//       filter: "true",
//     },
//   ],
//   actions: {
//     create: true,
//     edit: true,
//     delete: false,
//   },
// };
export default TABLE_CONFIG;
